### ISSUE TITLE
ofxMVG Binaries

### ISSUE THREAD

**Issue by natowi** [poparteu/ofxMVG#32]
Would be nice to have...
https://groups.google.com/forum/#!topic/alicevision/1CMyhsQZ0PI

**Comment by fabiencastan** [comment]
This project is not ready for end users and is not maintained for now. It has been developed for testing and analyzing the camera tracking algorithms.
It may become active again in the future, but not for now.

**Comment by natowi** [comment]
Thanks, good to know.

**Comment by fabiencastan** [comment]
I should have add this to the README but...
